language: generic
os: linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t yujinggao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yujinggao/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-2-611006255447"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY